### ISSUE TITLE
Refine Push_Nearby or Gust

### ISSUE THREAD

**Issue by bonn2** [MinecoreNetwork/ElementalArmor#12]
Now that we have util.Counter, I think it would be cool if we made it so that holding down crouch charged up this ability and jumping "releases" it to push stuff away

**Comment by Jaimss** [comment]
Love this idea. Maybe a similar thing for explosion should be implemented as well. (I'll open an issue if you agree, and make it happen later today)

**Comment by bonn2** [comment]
Yeah sounds awesome! I think we are onto something here.

**Comment by Jaimss** [comment]
Definitely
