### ISSUE TITLE
Gambling Plugin

### ISSUE THREAD

**Issue by EpicGuyTy** [MinecoreNetwork/ElementalArmor#17]
Armor should upgrade based on killing our custom mobs, not mobs from the normal worlds but dimensions,temples,ect
There should be a mandatory turn off functions of armor in spawn areas etc ect
Armor should have a percentage of progress shown in some way.
Charms should be easily taken off and put back on.

**Comment by Jaimss** [comment]
is this related to elemenetalarmor or a separate plugin?

**Comment by bonn2** [comment]
I'm teaching ty github right now

**Comment by Jaimss** [comment]
ah ok lol

**Comment by bonn2** [comment]
He's getting there 👍🏻

**Comment by Jaimss** [comment]
lets add him to this org, and then we can put him on the @MinecoreNetwork/enigma team and we can move this discussion over there

**Comment by bonn2** [comment]
Yeah

**Comment by Jaimss** [comment]
opened an enigma discussion
https://github.com/orgs/MinecoreNetwork/teams/enigma/discussions/1
