### ISSUE TITLE
Add /libs/ directory to the project

### ISSUE THREAD

**Issue by bonn2** [MinecoreNetwork/ElementalArmor#27]
Currently the only thing in /libs/ is ArmorEquipEvent, and reading through the [README](https://github.com/Arnuh/ArmorEquipEvent/blob/master/README.md) on it's github, we should be clear to add it to the repo to allow for easier pulling and cloning

**Comment by bonn2** [comment]
@Jaimss what do you think about this?

**Comment by Jaimss** [comment]
I see no issue with this. jar size is only 14kb, which is really small. I say we do it

**Comment by Jaimss** [comment]
also if we ever update the lib, everyone can just pull the change

**Comment by bonn2** [comment]
Yeah, this will definitely make it more streamlined
